### ISSUE TITLE
Silverlight version

### ISSUE THREAD

**Issue by mahdiit** [jariq/Pkcs11Interop#14]
is there plan to run this moudle in silverlight?

i use library and convert as silverlight version but there is some errors and diffrent on someobject that must be cast

any hope for silverlight 5?

**Comment by jariq** [comment]
Hello mahdiit, currently I have no plans to create Silverlight version of Pkcs11Interop as there seems to be a lack of demand for such version. You are actually the first person asking for it. Could you please share more info about the conversion process you are using?

**Comment by mahdiit** [comment]
hi
we have a web application that use security module like smart cart or token for login, as solution for client side for web application we are using applet and java,

silverlight work inside browser with no dependency to .net framework just a plugin and can read token and do other works that we need

if your library can have silverlight version we can develop some app that work without buggy applet that need java runtime also has more security again java applet.

but i am change your library and build my own silverlight class library, googling problems and fix them 
some Marshal method needs change and some win32 exception must change

 but if there was a official release it can be better
i see some commercial product like NCryptoki (very similar to your product and some class is same as your lib) that they have silverlight version  but open source solution for security module always is best 

Mahdi Yousefi
Web developer

**Comment by jariq** [comment]
Thanks for the detailed info Mahdi. I have managed to get Pkcs11Interop partialy working inside silverlight application but it requires [elevated trust](http://msdn.microsoft.com/en-us/library/ee721083(v=vs.95).aspx) otherwise it is unable to access unmanaged PKCS#11 library. I am currently failing to understand why would anyone consider silverlight application to be a better choice than ActiveX component which can utilize full power of .NET and use already available versions of Pkcs11Interop. Have you considered the creation of a custom ActiveX component?

**Comment by mahdiit** [comment]
yes, we think 
at first of all solutions we have activex but activex run only inside internet explorer
it sounds that Microsoft decide to retire IE in next version of windows and new browsers does not like activex (code name spartan)
Microsoft also has an activex component with name capicom.dll that works well as our needs can read certificates from windows cert store and sign pcks messages.

but we need multi platform, browsers solutions like silverlight and java applet

i use trusted silverlight 
it has two simple step:
enable a registry key
sign silverlight app with valid signature 

better than activex with .net framework installer or applet with JRE

**Comment by AntonioGa** [comment]
Dear, I'm also interested in Silverlight 5 Version. My use case is the same as mahdiit. I'm according full-trust is a must.

**Comment by jariq** [comment]
I'll try to start experimental branch or new repository for Silverlight5 version next week. I will post more details here when available.

**Comment by mahdiit** [comment]
thanks from your works
i can share my changes in your library to work with silverlight with you if you need
i build and use silverlight version but can not test all of it

**Comment by jariq** [comment]
Thanks Mahdi, but there is no need to share your changes. I would like to step through the problems by myself alone so I can learn more about Silverlight specifics and also test the implementation thoroughly.

**Comment by jariq** [comment]
Hey guys, I would like to know your opinion on these topics:

1. **Have you ever managed to run Silverlight app in-browser with elevated trust on OS X?**
 I can't get it working and according to [MSDN forum post by Pete Brown](https://social.msdn.microsoft.com/Forums/silverlight/en-US/8168a004-aa7d-497a-96d4-849238b74567/silverlight-5-trusted-in-browser-instructions-for-mac-users?forum=silverlightgen) trusted in-browser execution is a Windows-only feature. If it is true then Silverlight version of Pkcs11Interop would be also Windows-only.

2. **Are you really performing [all steps required to enable in-browser execution with elevated trust](https://msdn.microsoft.com/en-us/library/gg192793%28v=vs.95%29.aspx) on Windows for your production applications?**
It is working for me flawlessly but from my experience setting registry keys and importing code signing certificate into the trusted publishers store is a show stopper for regular users.

**Comment by mahdiit** [comment]
1- yes, windows only working for in browser
2- need a nsis setup script only about 60-70kb to run on user computer to enable registry key and add selfsign cerfiticate to windows store or use a valid certificate

**Comment by AntonioGa** [comment]
Correct.

**Comment by AntonioGa** [comment]
If you like I can contribute with Setup (Registry Key and Certificate)

**Comment by jariq** [comment]
Thank you guys for your prompt answers. They were really helpful.

@AntonioGa thank you for your offer but I plan to provide just the assembly optimized for Silverlight 5. It is up to each individual developer/integrator to link the assembly to his application and to sort runtime prerequisites in an optimal way for his deployment scenario.

BTW I have managed to get the full test suite running today in Silverlight test application. It has identified a few minor problems that still need to be solved but I expect to publish the code (Windows-only for now) in no more than a week.

**Comment by mahdiit** [comment]
Silverlight out-browser works on all os

**Comment by jariq** [comment]
Yes, trusted Silverlight application works for me Out-of-Browser on OS X Yosemite but I am getting `System.MethodAccessException` when I want to pinvoke unmanaged function such as `dlopen()` which dynamically loads PKCS#11 library ([dlopen](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/dlopen.3.html) is unix equivalent of [LoadLibrary](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175%28v=vs.85%29.aspx) function). I have found MSDN article ["How to: Call Unmanaged Code from Trusted Applications"](https://msdn.microsoft.com/en-us/library/hh560563(v=vs.95).aspx) which states that:

> Platform invoke in Silverlight can only be used on computers running the Windows operating system. There is no Mac support.

If this is true then there is nothing I can do to make Silverlight version work on OS X.

**Comment by AntonioGa** [comment]
In my application, I don't have to support Mac and Linux users.

**Comment by jariq** [comment]
Hey guys, I have just pushed the changes required for Silverlight to the master branch. Source code can be retrieved via git or downloaded as a [ZIP archive](https://github.com/jariq/Pkcs11Interop/archive/master.zip). Please let me know if it works for you.

**Comment by mahdiit** [comment]
thanks, i am testing and inform you about any problem, if exsist

**Comment by mahdiit** [comment]
i test for my work reading slots, keys, sign
no problem in silver light

thanks

**Comment by jariq** [comment]
Great. Thanks for letting me know.
