### ISSUE TITLE
pkcs11 proxy

### ISSUE THREAD

**Issue by armando-basile** [jariq/Pkcs11Interop#15]
Hi Jariq,
i try to use an ARM device (cubietruck with AllWinner A20) for production environment. I have a network hsm that drive from linux x86_64 whit supplier pkcs11 lib that use a public pkcs11 interface but send requests on network vs hsm with private protocol. 
To drive this hsm from arm device without supplier libraries i think that could be used a pkcs11 proxy: a pkcs11 server on x86_64 pc that switch request vs real hsm.
What do you think about ?

**Comment by jariq** [comment]
Hello Armando,

I believe it may work. You may encounter some issues if the size of unmanaged long on x86_64 machine is different than the size of unmanaged long on the ARM machine but careful implementation can take of that.

BTW I am aware of [caml-crush](https://github.com/ANSSI-FR/caml-crush) and [pkcs11-proxy](https://github.com/SUNET/pkcs11-proxy) open source solutions but I haven't tried them yet. I've seen also some [patches](http://lists.freedesktop.org/archives/p11-glue/2014-November/000515.html) implementing this feature in [p11-kit](http://p11-glue.freedesktop.org/p11-kit.html).

Feel free to update this issue with your findings.
