### ISSUE TITLE
Retrieving keys from HSM

### ISSUE THREAD

**Issue by retzel15** [jariq/Pkcs11Interop#18]
Hi may I just ask. Is there a way to extract generated keys from HSM and use it externally? If so, how?
I tried to use generatekey function it returned an object but it is encrypted. Is there a way to get the real key? 
Thanks.

**Comment by jariq** [comment]
It depends on the type of HSM you are using but in general all key objects with `CKA_EXTRACTABLE` attribute set to `CK_TRUE` can be exported. Which exact attributes hold private parts of the key depends on the key type i.e. it is `CKA_VALUE` attribute for `CKK_AES` keys. You can consult [PKCS#11 specification](http://pkcs11interop.net/rsa-pkcs11-2.20/pkcs-11v2-20.pdf) for more details and I believe you may find following code sample helpful:

```csharp
using System;
using System.Collections.Generic;
using Net.Pkcs11Interop.Common;
using Net.Pkcs11Interop.HighLevelAPI;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            using (Pkcs11 pkcs11 = new Pkcs11(@"softhsm2.dll", true))
            {
                using (Session session = pkcs11.GetSlotList(true)[0].OpenSession(false))
                {
                    session.Login(CKU.CKU_USER, "11111111");

                    // Generate non-exportable AES key and try to export it
                    List<ObjectAttribute> key1Attributes = new List<ObjectAttribute>();
                    key1Attributes.Add(new ObjectAttribute(CKA.CKA_CLASS, CKO.CKO_SECRET_KEY));
                    key1Attributes.Add(new ObjectAttribute(CKA.CKA_KEY_TYPE, CKK.CKK_AES));
                    key1Attributes.Add(new ObjectAttribute(CKA.CKA_VALUE_LEN, 32));
                    key1Attributes.Add(new ObjectAttribute(CKA.CKA_EXTRACTABLE, false)); // key1 won't be exportable

                    ObjectHandle key1Handle = null;
                    using (Mechanism mechanism = new Mechanism(CKM.CKM_AES_KEY_GEN))
                        key1Handle = session.GenerateKey(mechanism, key1Attributes);

                    ObjectAttribute key1Value = session.GetAttributeValue(key1Handle, new List<CKA>() { CKA.CKA_VALUE })[0];
                    if (key1Value.CannotBeRead != true)
                        throw new Exception("Non-exportable key can be exported");

                    session.DestroyObject(key1Handle);

                    // Generate exportable AES key and export it
                    List<ObjectAttribute> key2Attributes = new List<ObjectAttribute>();
                    key2Attributes.Add(new ObjectAttribute(CKA.CKA_CLASS, CKO.CKO_SECRET_KEY));
                    key2Attributes.Add(new ObjectAttribute(CKA.CKA_KEY_TYPE, CKK.CKK_AES));
                    key2Attributes.Add(new ObjectAttribute(CKA.CKA_VALUE_LEN, 32));
                    key2Attributes.Add(new ObjectAttribute(CKA.CKA_EXTRACTABLE, true)); // key2 will be exportable

                    ObjectHandle key2Handle = null;
                    using (Mechanism mechanism = new Mechanism(CKM.CKM_AES_KEY_GEN))
                        key2Handle = session.GenerateKey(mechanism, key2Attributes);

                    ObjectAttribute key2Value = session.GetAttributeValue(key2Handle, new List<CKA>() { CKA.CKA_VALUE })[0];
                    if (key2Value.CannotBeRead != false)
                        throw new Exception("Exportable key cannot be exported");

                    byte[] key = key2Value.GetValueAsByteArray();

                    session.DestroyObject(key2Handle);

                    session.Logout();
                }
            }
        }
    }
}
```

**Comment by retzel15** [comment]
All is good. Thank you very much jariq. 
But what if I want to store my own key value into the HSM? I tried to createObject but it returned that I have incomplete template. Thanks

**Comment by retzel15** [comment]
Sorry for the trouble man. I successfully created a key with my own template. I used this template:

byte[] keyValue = { 0xE4, 0xDF, 0x8E, 0xA3, 0xC3, 0xDE, 0x61, 0x7C, 0x09, 0x81, 0xB5, 0xCD, 0x0B, 0x31, 0x4E, 0xFA };
                    byte[] ckaID = session.GenerateRandom(20);
		    int valueLength = 32;
	            string keyLabel = @"masterKey";
                    // Prepare attribute template of new key
                   
                    List<ObjectAttribute> keyAttributes = new List<ObjectAttribute>();
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_CLASS, CKO.CKO_SECRET_KEY));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_TOKEN, true));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_PRIVATE, false));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_VALUE, keyValue));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_KEY_TYPE, CKK.CKK_AES));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_VALUE_LEN, valueLength));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_LABEL, keyLabel));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_EXTRACTABLE, true));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_ID, ckaID));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_ENCRYPT, true));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_VERIFY, true));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_VERIFY_RECOVER, true));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_WRAP, true));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_MODULUS_BITS, 1024));
                    keyAttributes.Add(new ObjectAttribute(CKA.CKA_PUBLIC_EXPONENT, new byte[] {        0x01, 0x00, 0x01 }));

                    // Create object
                    ObjectHandle objectHandle = session.CreateObject(keyAttributes);

Posting it here. It might help others wanting an answer. Thanks :)
