### ISSUE TITLE
Retrieve non-expired Private Key(s) from CardOS Card?

### ISSUE THREAD

**Issue by jbattermann** [jariq/Pkcs11Interop#20]
Hello there Jaroslav,

I am currently starting to dig into card based data signing / signature generation and the PKI infrastructure here is based on Siemens / Atos CardOS and I was wondering how I could retrieve the currently valid, non-expired private key from a card.

I can log in & create a CKU.CKU_USER session with the correct pin, but I am a bit confused how to retrieve the non-expired, private key(s) for / from the currently plugged in card.

In your test project there's a Helper class that generates a public/private key, but as far as I understand it, those are only temporary and for the purpose of your test-project, right? Or maybe I am missing something here :-/

I.e. I have 6 certificates on my card, and when calling

```
using (Pkcs11 pkcs11 = new Pkcs11(@"C:\Windows\System32\cardos11_64.dll", true))
{
  // Find first slot with token present
  var slot = pkcs11.GetSlotList(true).FirstOrDefault();

  using (var session = slot.OpenSession(true))
  {
    session.Login(CKU.CKU_USER, "12345678");

    List<ObjectAttribute> keyAttributes = new List<ObjectAttribute>
    {
        new ObjectAttribute(CKA.CKA_TOKEN, true),
        new ObjectAttribute(CKA.CKA_PRIVATE, true),
        new ObjectAttribute(CKA.CKA_SENSITIVE, true),
        new ObjectAttribute(CKA.CKA_SIGN, true)
    };

    var objectHandleForPotentiallyPrivateKeys = session.FindAllObjects(keyAttributes);
  }
}
```

.. I get 6 handles back - out of those 6 handles/certificates I know 4 are already expired.. so I was wondering how to tell which of those handles correspond to which certificate and how I'd get the private and public key for the other two?

Or maybe I am totally wrong here, but any kind of help / pointer in the right direction would be highly appreciated.

Cheers & thanks,
-Jörg

**Comment by jariq** [comment]
Hello Jörg

> I can log in & create a CKU.CKU_USER session with the correct pin, but I am a bit confused how to retrieve the non-expired, private key(s) for / from the currently plugged in card.

Usually it is the certificate (not private key) that expires.

> In your test project there's a Helper class that generates a public/private key, but as far as I understand it, those are only temporary and for the purpose of your test-project, right? Or maybe I am missing something here :-/

Yes, those are only temporary test keys. In real world scenarios keys are already present on device and you need to find them with `session.FindAllObjects()` method.

> .. I get 6 handles back - out of those 6 handles/certificates I know 4 are already expired.. so I was wondering how to tell which of those handles correspond to which certificate and how I'd get the private and public key for the other two?

You can search for private keys specifically if you add `ObjectAttribute(CKA.CKA_CLASS, CKO.CKO_PRIVATE_KEY)` to your search template or for certificates specifically if you add `ObjectAttribute(CKA.CKA_CLASS, CKO.CKO_CERTIFICATE)` to your search template. Association between key and certificate objects is usually maintained with the value of `CKA_ID` attribute - both objects share the same value of this attribute. To find out the validity period of certificate object you need to read the value of its `CKA_VALUE` attribute and pass it to the constructor of `System.Security.Cryptography.X509Certificates.X509Certificate2` class which should provide more details such as a certificate validity period etc.

> Or maybe I am totally wrong here, but any kind of help / pointer in the right direction would be highly appreciated.

You can take a look at [Pkcs7SignatureGenerator](https://github.com/jariq/Pkcs7SignatureGenerator#list-private-keys-and-certificates-on-specified-token) application which performs basic token/object listing and should serve as a basic example of all the techniques I have mentioned in this comment.

Regards, Jaroslav

**Comment by jbattermann** [comment]
Hi Jaroslav,

awesome - thanks for the quick and helpful reply! One last, 'remotely' related questions: is there a built-in / implicit way to trigger the Windows Pin-Entering dialog / ask the user to insert the smart card and then for the pin for the card?

While I could use P/Invoke to use the Windows CredUi* dialogs myself, maybe there's a more elegant, integrated way to do so.


Thanks,
-Jörg

**Comment by jariq** [comment]
None I am aware of. I am using custom dialogs most of the time.

**Comment by jbattermann** [comment]
Alright - thanks a lot Jaroslav.. the Pkcs7SignatureGenerator project is really helpful!
