### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by lkn2993** [jariq/Pkcs11Interop#22]
Sorry to bother you again, but this problem was considered a new issue so I had to post it in separate thread.

It seems that in your other project(https://github.com/jariq/Pkcs11Interop.PkiUtils/tree/master/src/Pkcs11Interop.PkiUtils)

You have a template which generates PKCS#10 (To pass it to CA for having it signed)
However it does not provide any example on a self signed certificate.

I wonder, can this method even be achieved using bouncycastle you used for generating pkcs#10, or are there any libraries out there that can delay the certificate signature process and let the application sign the certificate itself?
 
Thanks in advance.

**Comment by jariq** [comment]
Let me first clearly answer your question: **BouncyCastle is all you need.**

BouncyCastle works out-of-the-box only with the cryptographic keys that can be exposed into the host memory. However one must not forget that BouncyCastle is general purpose cryptographic library and if you are willing to do a little extra work on lower level APIs you can use it also with the keys that cannot be exposed in the host memory. In your case you would need to use BouncyCastle  (low level APIs) to create X.509 structure and then use PKCS#11 library for a low level signature. This approach requires you to do more coding and to have much deeper understanding of X.509, ASN.1 and related technologies but it certainly can be done.

BTW I am little confused of your PKCS#11 related posts here [[1]](https://github.com/jariq/Pkcs11Interop/issues/19) and on stackowerflow [[1]](http://stackoverflow.com/questions/34528927/create-unsigned-certificate-in-c-sharp) [[2]](http://stackoverflow.com/questions/33872028/directly-signing-an-office-word-document-using-xml) [[3]](http://stackoverflow.com/questions/33659217/create-a-certificate-for-microsoft-office-using-pkcs11-library) and I am failing to understand what is your goal with this technology. Maybe you could share more high level details of your project so I can better understand your needs? Feel free to drop me an e-mail to jaroslav.imrich@gmail.com if you don't want to discuss it publicly.

**Comment by lkn2993** [comment]
Then lets continue the discussion in the mails then.
